### ISSUE TITLE
Not able to fetch location

### ISSUE THREAD

**Issue by ShivamDev31** [sdoward/RxGoogleMaps#7]
Hi,

Thanks for the great lib. I'm facing an issue. I'm not able to fetch the user location.
Code : https://gist.github.com/ShivamDev31/891737d11258931be01463322cdfb133

Using the lib for rx location : https://github.com/mrmans0n/smart-location-lib
and tried another lib but same issue.
So basically when I try smart loc lib without maps libs it works fine but not able to set the location when I try it with maps lib.
Can you please look into the source gist above and let me know where I'm doing wrong?

Trying to make it work since hours but it didn't work out.

**Comment by sdoward** [comment]
This lib doesn't retrieve locations so I can't image it is an issue with this library. I can't see where the problem is at a glance but there is some odd usage of RxJava in there so that might be an issue. I would spend some time looking into the combine operators http://reactivex.io/documentation/operators.html

FlatMap is your friend :)
